title: Eduardo Ramirez
email: contact@eduramirez.com
baseurl: ""
url: "https://eduramirez.com"

# Multilingual settings
languages: ["en", "es", "ca"]
default_lang: "en"
exclude_from_localizations: ["javascript", "images", "css", "scripts"]

# Build settings
markdown: kramdown
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-feed
  - jekyll-seo-tag

# Allow custom HTML in posts
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true